services:
  db:
    image: postgres:17
    container_name: fintrack-db
    environment:
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack123
      POSTGRES_DB: fintrack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/fintrack"
      SPRING_DATASOURCE_USERNAME: "fintrack"
      SPRING_DATASOURCE_PASSWORD: "fintrack123"
      MAIL: "robbyknee85@gmail.com"
      MAIL_PASSWORD: "rawz xfkb tadc etdg"
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
