version: "3.8"

services:
  fintrack-db:
    image: postgres:15
    container_name: fintrack-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fintrack
    ports:
      - "5433:5432"   # Host port 5433 â†’ Container port 5432
    volumes:
      - fintrack-pro_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  fintrack-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fintrack-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://fintrack-db:5432/fintrack
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - fintrack-db
    restart: unless-stopped

volumes:
  fintrack-pro_pgdata:
